# https://github.com/jenkins-infra/.github/blob/master/.github/release-drafter.yml
_extends: github:jenkins-infra/.github:/.github/release-drafter.yml
# Semantic versioning: https://semver.org/
version-template: $MAJOR.$MINOR.$PATCH
tag-template: v$NEXT_MINOR_VERSION
name-template: v$NEXT_MINOR_VERSION
