# .kodiak.toml
# Minimal config. version is the only required field.
version = 1
[merge.automerge_dependencies]
versions = ["minor", "patch"]
# only automerge by upgrade version for pull requests authored by dependabot.
usernames = ["dependabot"]
