apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    jenkins: "agent"
    job: "plugin-site"
spec:
  tolerations:
    - key: "os"
      operator: "Equal"
      value: "linux"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                  - linux
  restartPolicy: "Never"
  containers:
    - name: "node"
      image: "node:18"
      securityContext:
        privileged: false
      tty: true
      command:
      - cat
    - name: "blobxfer"
      image: "mcr.microsoft.com/blobxfer:1.11.0"
      command:
      - cat
      securityContext:
        privileged: false
      tty: true
