export const ui = {
  activeCategories: [],
  activeLabels: [],
  activeQuery: '',
  firstVisit: true,
  isFetchingPlugin: false,
  isFiltered: false,
  isSearching: false,
  limit: 50,
  page: 1,
  pages: 1,
  plugin: null,
  plugins: [],
  query: '',
  showFilter: false,
  showResults: false,
  sort: 'relevance',
  total: 0,
  view: 'Tiles'
};
